### PR TITLE
remove defunct instruction

### PR DESCRIPTION
**Pull request by matkoniecz**
https://github.com/maplibre/maplibre-plugins-android/pull/5#issuecomment-1172906118

### CODE REVIEW

**Review by wipfli — APPROVED** [review]
It would be really great if you could go to maplibre/maplibre and open a repo onboarding issue there, @matkoniecz. I think there are many small tasks like license that we need to do for this repo...

**Comment by matkoniecz** [comment]
> open a repo onboarding issue there

I do not understand what you mean here

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre has an issue template for reop on-boarding.

**Comment by wipfli** [comment]
Here is an example https://github.com/maplibre/maplibre/issues/61

**Comment by wipfli** [comment]
I think it would make sense to open such an on-boarding issue for this repo here...

**Pull request merged**
