### PR TITLE
Fix : Missing init key for maptiler and update style

### PR DESCRIPTION
**Pull request by ravenfeld**
It's quite strange that the examples don't work. It doesn't help developers. 
Let's start by making sure it doesn't crash any more 

https://github.com/maplibre/maplibre-plugins-android/issues/62

### CODE REVIEW

**Review by louwers — CHANGES_REQUESTED** [review]
I suggest that we replace the styles with styles that do not require an API key.

For example:

https://tiles.openfreemap.org/styles/liberty

https://tiles.openfreemap.org/styles/positron

https://tiles.openfreemap.org/styles/bright

https://tiles.versatiles.org/assets/styles/colorful.json

https://americanamap.org/style.json

**Comment by ravenfeld** [comment]
Should I still use `WellKnownTileServer` and `getPredefinedStyle`? 
Because I don't know much about it as I don't use it on my personal project.

**Comment by louwers** [comment]
I would not use them, because we will remove them at some point from MapLibre Native.

I created a `TestStyles.kt` file for MapLibre Native: https://github.com/maplibre/maplibre-native/blob/main/platform/android/MapLibreAndroidTestApp/src/main/java/org/maplibre/android/testapp/styles/TestStyles.kt

**Comment by ravenfeld** [comment]
```
enum class OpenFreeMapStyle(val url:String){
    POSITRON(url = "https://tiles.openfreemap.org/styles/positron"),
    BRIGHT(url = "https://tiles.openfreemap.org/styles/bright"),
    LIBERTY(url = "https://tiles.openfreemap.org/styles/liberty")
}
```

Here's what I suggest. So we use this enum instead of `getPredefinedStyle `

**Comment by louwers** [comment]
I like `TestStyles` class better, might be that we have to replace OpenFreeMap with something else...

**Comment by ravenfeld** [comment]
@louwers Are you happy with my proposal?

**Review by louwers — APPROVED** [review]

**Comment by louwers** [comment]
Yes, thanks!

**Comment by klokan** [comment]
😢

**Comment by ravenfeld** [comment]
@klokan is something wrong?

**Comment by louwers** [comment]
@ravenfeld @klokan is the CEO of MapTiler. 🙂

**Pull request merged**
